"""
Makes Gremlin behave the way you actually want to use it: it's the one
interface you talk to, it answers on its own whenever it can, and it
only reaches out to other registered models (local or API) when its
own answer looks uncertain. Whatever it learns from that consultation
gets written to a log so the exact same question doesn't need to
trigger a consult again.

Two things this file is careful about:

1. Other models are information sources during a consult, never the
   ones actually speaking to the user. The first pass classifies the
   question's topic and routes to the single best-fit specialist for it
   (see gremlin_core/specialists.py's `specialists:` config) -- never a
   broadcast to the whole roster, which on an 8GB card meant loading
   local models one at a time and made a single consult take hours.
   That one answer is kept only if it's actually confident (not just a
   successful call -- an "I don't know" that came back with
   result.ok=True still doesn't count as help). If it wasn't confident,
   `last_resort_model` (if configured, e.g. Gemini) gets one dedicated
   final check -- not just another candidate in the same pass. Whatever
   is found, the final synthesis is always generated by calling the
   persona itself (`gremlin`), so the voice and personality are always
   Gremlin's own -- the other models only ever supplied the raw material.

2. This deliberately does NOT auto-trigger a code edit. Consulting
   other models to answer a question is safe to automate -- worst case,
   you get a synthesized answer. Auto-editing Gremlin's own source
   based on whatever a user happened to type is a different risk
   entirely: it would mean any message, including an adversarial one,
   could cause the system to rewrite itself with no review step. So
   when a consult reveals an actual capability gap, this only ever
   *suggests* a goal string for the existing
   `python main.py improve ... --apply` flow -- a human still decides
   whether that patch is worth proposing and applying.
"""
from __future__ import annotations
import dataclasses
import json
import os
import random
import re
import time
from contextlib import contextmanager
from typing import Optional

from .router import Router
from . import away_sync
from . import specialists as specialists_mod
from .backends.base import GenerationResult

# A file-based "is gremlin currently generating an answer" signal --
# deliberately just a file, not a socket or shared-memory flag, so any
# process can read it (the desktop hologram window and `gremlin serve`
# are separate processes; this is the simplest thing that works across
# that boundary). Written/removed around the one place both the CLI
# `chat` command and the server's /chat route actually call to get an
# answer in Gremlin's own voice -- see consult_and_learn below -- so
# every real "Gremlin is talking" moment sets it, with nothing to keep
# in sync at each call site.

UNCERTAINTY_MARKERS = [
    "i don't know", "i do not know", "i'm not sure", "i am not sure",
    "i don't have enough information", "i do not have enough information",
    "i cannot determine", "i can't determine", "unclear to me",
    "i'm unable to determine", "i am unable to determine",
    "i don't have access to", "i do not have access to",
    "not certain", "no information about this", "i have no way to know",
]

CONSULT_SYNTHESIS_PROMPT = (
    "You are answering a question using research gathered from other AI "
    "models, because your own first answer wasn't confident enough. Read "
    "the gathered answers below and give ONE clear, direct answer to the "
    "original question, in your own voice. Don't mention the consultation "
    "process or name which model said what -- just answer well, as yourself."
)


def seems_uncertain(text: str) -> bool:
    if not text or len(text.strip()) < 3:
        return True
    lowered = text.lower()
    return any(marker in lowered for marker in UNCERTAINTY_MARKERS)


def _log_path(root: str) -> str:
    path = os.path.join(root, "data", "learning_log.jsonl")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return path


def load_learned_answer(root: str, prompt: str) -> Optional[str]:
    """Exact-match lookup against past consultations. Intentionally
    simple -- no embeddings or fuzzy matching -- this is a starting
    point, not a full memory system."""
    path = _log_path(root)
    if not os.path.exists(path):
        return None
    with open(path, "r") as f:
        for line in f:
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            if entry.get("prompt") == prompt:
                return entry.get("final_answer")
    return None


def append_learning_log(root: str, entry: dict) -> None:
    entry["timestamp"] = time.time()
    with open(_log_path(root), "a") as f:
        f.write(json.dumps(entry) + "\n")


def _talking_marker_path(root: str) -> str:
    return os.path.join(root, "data", "talking.marker")


@contextmanager
def _talking(root: str):
    """Marks Gremlin as talking for the duration of the wrapped block --
    best-effort, same "a missed write/cleanup isn't fatal" spirit as the
    rest of this file's file-based state (learning log, away-sync)."""
    path = _talking_marker_path(root)
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(str(time.time()))
    except OSError:
        pass
    try:
        yield
    finally:
        try:
            os.remove(path)
        except OSError:
            pass


def is_talking(root: str) -> bool:
    """Read side of the marker -- used by the desktop hologram window
    (polled) and, indirectly, documents what the Android app gets
    pushed directly instead (see MainActivity's evaluateJavascript
    calls, which don't need this at all). A marker older than 60s reads
    as False -- guards against a hung "talking" hologram forever if a
    process ever got killed between writing and removing it."""
    path = _talking_marker_path(root)
    if not os.path.exists(path):
        return False
    try:
        age = time.time() - os.path.getmtime(path)
    except OSError:
        return False
    return age < 60


def _confident_results(results: dict) -> dict:
    """Only the ones that actually succeeded AND don't themselves read
    as uncertain -- a model that answered 'I'm not sure either' still
    counts as ok=True, but shouldn't be treated as a real contribution."""
    return {name: r for name, r in results.items() if r.ok and not seems_uncertain(r.text)}


def _memory_file_path(root: str) -> str:
    """A plain, human-editable text file living next to the project
    (in ~/Downloads, one level up from the gremlin repo itself) rather
    than inside data/ -- so it's easy for mickey to open directly in a
    text editor, and so it's never touched by the git-based auto-update
    timer. This is the actual fix for "memory doesn't last": the
    learning log and away-sync log are both narrow, single-purpose logs
    that only ever get read back in specific situations (exact-match
    cache, away-mode replay); nothing before this gave Gremlin a place
    to keep general facts across sessions."""
    return os.path.join(os.path.dirname(root.rstrip(os.sep)), "gremlin_memory.txt")


def _load_memory_notes(root: str, max_chars: int = 6000) -> str:
    """Read back whatever's in the memory file, most recent lines first
    trimmed to a bounded size -- this is meant to be durable notes fed
    into every prompt as background, not an unbounded context dump."""
    path = _memory_file_path(root)
    if not os.path.exists(path):
        return ""
    with open(path, "r") as f:
        text = f.read().strip()
    if not text:
        return ""
    if len(text) > max_chars:
        text = text[-max_chars:]
    return "Things you (Gremlin) have been told to remember about the user, across all past sessions:\n" + text


def remember_fact(root: str, text: str) -> None:
    """Appends a durable, timestamped note to the memory file. Unlike
    learning_log.jsonl (auto-populated from consults) or away_session_log
    (auto-populated from away-mode), this is the one memory store the
    user writes to directly, by telling Gremlin to remember something in
    conversation -- see the "remember" trigger in consult_and_learn."""
    path = _memory_file_path(root)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    stamp = time.strftime("%Y-%m-%d %H:%M")
    if not os.path.exists(path):
        header = (
            "# Gremlin's memory\n"
            "# Plain text, one note per line -- edit this file yourself any time,\n"
            "# or just tell Gremlin \"remember ...\" in chat and it'll append here.\n"
            "# Read back into context on every message, so nothing written here\n"
            "# is forgotten between sessions.\n\n"
        )
        with open(path, "w") as f:
            f.write(header)
    with open(path, "a") as f:
        f.write(f"- [{stamp}] {text}\n")


REMEMBER_PREFIXES = ("remember that ", "remember: ", "remember ")

# --- automatic long-term notes ---------------------------------------
#
# Beyond the explicit "remember X" path, Gremlin saves durable facts it
# notices on its own -- a name, a preference, an ongoing project detail,
# hardware -- to the SAME long-term memory file. Two safeguards keep that
# from turning the memory file into noise:
#
#  1. A tight pre-filter. Only a first-person STATEMENT of fact ("my dog
#     is named Cyclops", "I use Manjaro") is even considered. Questions,
#     commands, chitchat, and anything not about the user are skipped
#     with no model call at all -- so this costs nothing on most turns.
#  2. Dedup + an [auto] tag. A note already recorded isn't written again,
#     and auto-saved notes are tagged so they're distinguishable from
#     ones the user explicitly asked for, and easy to prune.

_PERSONAL_FACT_HINT = re.compile(
    r"\b("
    r"my (name|dog|cat|pet|wife|husband|partner|kid|son|daughter|job|"
    r"desktop|laptop|phone|gpu|card|setup|project|goal|birthday|address|"
    r"email|favou?rite|preference)"
    r"|i(\x27m | am | have | use | run | prefer | like | hate | love | work | live |"
    r" own | drive | need | want | always | never | usually )"
    r"|we (are |have |use |run |prefer |live |own )"
    r"|call me\b"
    r"|remember this"
    r")",
    re.IGNORECASE,
)

_AUTONOTE_SYSTEM = (
    "You extract at most ONE durable fact worth remembering long-term about the user, "
    "from their message. Durable = still true next week: a name, a preference, an ongoing "
    "project, their hardware, a relationship, a goal. NOT questions, NOT one-off requests, "
    "NOT transient state (\"I'm tired\"), NOT anything about you the assistant. "
    "Reply with ONLY the fact as a short third-person note (e.g. \"User's dog is named "
    "Cyclops\"), or exactly NONE if there is nothing durable. No preamble, no quotes."
)


def looks_like_personal_fact(message: str) -> bool:
    """Cheap gate: is it even worth a model call to extract a note?"""
    m = (message or "").strip()
    if len(m) < 6 or m.endswith("?"):
        return False
    return bool(_PERSONAL_FACT_HINT.search(m))


def _normalize_note(text: str) -> str:
    return re.sub(r"[^a-z0-9 ]", "", (text or "").lower()).strip()


def note_already_saved(root: str, note: str) -> bool:
    """Dedup against what's already in the memory file, loosely -- an
    exact re-statement or a near-identical one shouldn't be saved twice."""
    path = _memory_file_path(root)
    if not os.path.exists(path):
        return False
    target = _normalize_note(note)
    if not target:
        return True  # nothing meaningful to save
    try:
        existing = open(path).read().lower()
    except OSError:
        return False
    return _normalize_note(note) in _normalize_note(existing)


def parse_autonote(raw: str) -> Optional[str]:
    """A model's autonote reply -> a fact string, or None."""
    if not raw:
        return None
    text = raw.strip().strip('"').strip()
    # Models sometimes prepend "Note:" or wrap it -- take the first line.
    text = text.splitlines()[0].strip() if text else ""
    if not text or text.upper().startswith("NONE") or len(text) < 4:
        return None
    return text


async def maybe_autosave_note(router: "Router", persona_name: str, message: str, root: str) -> Optional[str]:
    """Notice and save a durable fact from the user's message. Best-effort:
    returns the saved note, or None if nothing worth keeping. Never raises
    -- a failed extraction must not affect the actual reply."""
    if not looks_like_personal_fact(message):
        return None
    try:
        result = await router.route(persona_name, message, system=_AUTONOTE_SYSTEM, max_tokens=60)
    except Exception:
        return None
    if not result.ok:
        return None
    note = parse_autonote(result.text)
    if not note or note_already_saved(root, note):
        return None
    remember_fact(root, f"[auto] {note}")
    return note


def _extract_remember_command(prompt: str) -> Optional[str]:
    stripped = prompt.strip()
    lowered = stripped.lower()
    for prefix in REMEMBER_PREFIXES:
        if lowered.startswith(prefix):
            fact = stripped[len(prefix):].strip()
            return fact or None
    return None


# --- on-demand teaching -----------------------------------------------
#
# "go learn about X" is different from an ordinary consult: a normal
# consult only ever fires when the primary's own answer looks uncertain
# (or, rarely, the random sample kept for data collection). This is an
# explicit request, so it always reaches out to the single best-fit
# specialist for X's topic (see specialists.classify_task_type) and
# always logs the result, regardless of how confident the primary would
# have been on its own.
#
# Recall is intentionally simple, matching load_learned_answer's existing
# "no embeddings, exact-match only" philosophy: what got learned is
# stored under a fixed canonical phrasing ("What do you know about
# X?"), and "what do you know about X" / "what did you learn about X"
# looks it up under that same phrasing. The durable version of recall --
# answering ANY phrasing of a question about X, not just this one -- is
# `gremlin finetune`, which folds everything learned this way into the
# primary itself.

LEARN_PREFIXES = ("go learn about ", "go learn ", "learn about ")
RECALL_PREFIXES = ("what do you know about ", "what did you learn about ", "do you know about ")

LEARN_SYNTHESIS_PROMPT = (
    "You are Gremlin, teaching yourself about a new topic using research gathered from "
    "one of your own specialist models. Write a clear, well-organized explanation of the "
    "topic in your own voice, as if this is genuinely something you now know. Don't mention "
    "the consultation process or which model helped -- just present the knowledge "
    "confidently, as yourself."
)


def _extract_learn_topic(prompt: str) -> Optional[str]:
    stripped = prompt.strip()
    lowered = stripped.lower()
    for prefix in LEARN_PREFIXES:
        if lowered.startswith(prefix):
            topic = stripped[len(prefix):].strip()
            return topic or None
    return None


def _extract_recall_topic(prompt: str) -> Optional[str]:
    stripped = prompt.strip().rstrip("?").strip()
    lowered = stripped.lower()
    for prefix in RECALL_PREFIXES:
        if lowered.startswith(prefix):
            topic = stripped[len(prefix):].strip()
            return topic or None
    return None


def _canonical_topic_prompt(topic: str) -> str:
    return f"What do you know about {topic.strip().rstrip('?').strip()}?"


async def _deliberate_candidate(
    router: Router, persona_name: str, topic: str, candidates: list,
) -> Optional[str]:
    """Which of this topic group's own models is actually best suited for
    `topic` -- a real per-topic pick, asked of gremlin itself (already
    resident, so this costs no extra model load), instead of always
    defaulting to the group's static priority order. Returns None (falls
    back to that static order) if there's only one candidate, or if the
    reply doesn't clearly name one of them."""
    if len(candidates) < 2:
        return candidates[0].name if candidates else None

    listing = "\n".join(f"- {c.name}: {c.notes or 'no notes'}" for c in candidates)
    system = (
        "You are picking which of your own sub-models is best suited to research a "
        "topic. Reply with ONLY the exact model name from the list below, nothing else."
    )
    prompt = f"Topic: {topic}\n\nAvailable models:\n{listing}\n\nWhich one is best suited?"
    try:
        result = await router.route(persona_name, prompt, system=system, max_tokens=30)
    except Exception:
        return None
    if not result.ok:
        return None
    reply = result.text.strip().lower()
    for c in candidates:
        if c.name.lower() in reply:
            return c.name
    return None


async def learn_about(router: Router, persona_name: str, topic: str, root: str) -> dict:
    """Ask the best-fit specialist for `topic`'s subject (never a
    broadcast), synthesize what it found in Gremlin's own voice, and log
    it unconditionally so it's both recallable (see _extract_recall_topic)
    and available as fine-tuning material next time `gremlin finetune`
    runs. Which specialist counts as "best-fit" isn't just the group's
    static priority order -- see _deliberate_candidate."""
    specialist_registry = specialists_mod.SpecialistRegistry.from_config(router.registry.raw_config)
    task_type = specialists_mod.classify_task_type(topic)
    candidates = specialist_registry.for_task(task_type)

    if not candidates:
        return {
            "answer": f"I don't have a specialist registered for that kind of topic yet, so there's nothing to learn it from.",
            "consulted": False,
            "from_memory": False,
            "contributors": [],
        }

    # Same VRAM-freeing reason as a normal consult: primary + a local
    # specialist likely can't both be resident at once on an 8GB card.
    if any(router.registry.get(c.name).info.kind == "local_gguf" for c in candidates):
        primary_name = router.registry.primary_model_name()
        if primary_name:
            await router.registry.get(primary_name).unload()

    # Ask gremlin itself which of this group's models actually fits the
    # topic, then bump that one to the front by priority so specialists.route
    # tries it first -- the rest stay as the normal error/empty-response
    # fallback chain, just re-anchored around the deliberated pick.
    chosen_name = await _deliberate_candidate(router, persona_name, topic, candidates)
    if chosen_name:
        candidates = [
            dataclasses.replace(c, priority=-1) if c.name == chosen_name else c
            for c in candidates
        ]
    ordered_registry = specialists_mod.SpecialistRegistry(candidates)

    routing = await specialists_mod.route(router, router.registry, ordered_registry, task_type, topic)
    # Free it immediately -- see the matching comment in
    # _consult_and_learn_inner for why (nothing else ever will, in a
    # one-shot CLI process, and the synthesis call right below needs to
    # reload the primary).
    if routing.specialist_used:
        try:
            await router.registry.get(routing.specialist_used).unload()
        except Exception:
            pass
    if not routing.routed or not routing.findings:
        return {
            "answer": f"Tried to learn about {topic}, but nobody in that group had anything usable"
                      f"{f' ({routing.error})' if routing.error else ''}.",
            "consulted": True,
            "from_memory": False,
            "contributors": [],
        }

    synth_prompt = f"Topic to learn: {topic}\n\nGathered research:\n{routing.findings}"
    synthesis = await router.route(persona_name, synth_prompt, system=LEARN_SYNTHESIS_PROMPT)
    final_answer = synthesis.text if synthesis.ok else routing.findings

    append_learning_log(root, {
        "prompt": _canonical_topic_prompt(topic),
        "topic": topic,
        "consulted_models": [routing.specialist_used],
        "consulted_texts": {routing.specialist_used: routing.findings},
        "final_answer": final_answer,
        "taught": True,
    })

    return {
        "answer": (
            f"{final_answer}\n\n(Learned this from {routing.specialist_used} -- ask "
            f'"what do you know about {topic}?" any time to hear it again, and it\'ll '
            f"be folded into my own answers permanently next time you run a fine-tune.)"
        ),
        "consulted": True,
        "from_memory": False,
        "contributors": [routing.specialist_used],
    }


def _recent_away_context(root: str, limit: int = 5) -> str:
    """This is the actual 'feed it back' piece: recent synced away-mode
    exchanges, handed to Gremlin as background so it can reference what
    was discussed while the user was out, rather than that history just
    sitting in a log file nobody reads. Deliberately small and bounded
    (last N entries) -- this is meant to be light context, not a full
    conversation-replay; it naturally ages out as new exchanges happen."""
    entries = away_sync.recent_entries(root, limit)
    if not entries:
        return ""
    lines = ["Recent conversation while the user was away from home (via phone, not this session):"]
    for e in entries:
        lines.append(f"- User asked: {e.get('prompt', '')}\n  You answered: {e.get('answer', '')}")
    return "\n".join(lines)


async def consult_and_learn(
    router: Router,
    persona_name: str,
    prompt: str,
    root: str,
    last_resort_model: Optional[str] = None,
    consult_sample_rate: float = 0.0,
    history: Optional[str] = None,
) -> dict:
    """Thin wrapper around _consult_and_learn_inner that marks Gremlin as
    'talking' (see _talking/is_talking above) for exactly the duration of
    a real answer -- this is the one place both the CLI `chat` command
    and the server's /chat route call to get one, so wrapping it here
    covers every real talking moment with nothing to keep in sync at
    each call site. See _consult_and_learn_inner's docstring for the
    actual answer-generation logic."""
    with _talking(root):
        return await _consult_and_learn_inner(
            router, persona_name, prompt, root,
            last_resort_model=last_resort_model,
            consult_sample_rate=consult_sample_rate,
            history=history,
        )


async def _consult_and_learn_inner(
    router: Router,
    persona_name: str,
    prompt: str,
    root: str,
    last_resort_model: Optional[str] = None,
    consult_sample_rate: float = 0.0,
    history: Optional[str] = None,
) -> dict:
    """
    0. If the message is a "remember ..." command, just write it to the
       durable memory file and confirm -- no model call needed. Every
       other prompt gets whatever's in that file folded into its context.
       "go learn about X" and "what do you know about X" are handled here
       too -- explicit teaching/recall, see learn_about's docstring.
    1. Check if this exact question was already learned -- answer from
       memory with zero model calls if so.
    2. Otherwise ask the persona (gremlin) directly.
    3. If confident, done -- already in Gremlin's own voice, since it
       came straight from the persona backend.
    4. If uncertain, classify the topic and route to the single best-fit
       specialist for it (see gremlin_core/specialists.py) -- never a
       broadcast to every registered model.
    5. If that wasn't confident and `last_resort_model` is set, try that
       one specifically as a final check.
    6. Whatever confident material was found (from step 4 and/or 5),
       hand it to the persona itself to produce the final answer --
       so the voice is always Gremlin's, never a raw forward of
       whichever model happened to answer.
    """
    remember_text = _extract_remember_command(prompt)
    if remember_text:
        remember_fact(root, remember_text)
        return {
            "answer": f"Got it, I'll remember that: {remember_text}",
            "consulted": False,
            "from_memory": False,
            "contributors": [],
        }

    # "go learn about X" -- explicit teaching, always reaches out to the
    # right specialist and always logs, unlike a normal (uncertainty- or
    # sample-triggered) consult. See learn_about's docstring.
    learn_topic = _extract_learn_topic(prompt)
    if learn_topic:
        return await learn_about(router, persona_name, learn_topic, root)

    # "what do you know about X" -- recall for something taught via
    # "go learn about X". Exact-match only, same philosophy as the general
    # learned-answer cache below; a miss just falls through to the normal
    # flow rather than a hard "I don't know".
    recall_topic = _extract_recall_topic(prompt)
    if recall_topic:
        taught_answer = load_learned_answer(root, _canonical_topic_prompt(recall_topic))
        if taught_answer is not None:
            return {"answer": taught_answer, "consulted": False, "from_memory": True, "contributors": []}

    # The exact-match learned-answer cache is a real feature for one-off
    # facts, but returning a canned answer MID-CONVERSATION is a big part
    # of the "forgets and reintroduces itself" feeling -- a cached "hi ->
    # I'm Gremlin" ignores everything just said. So only use it on a cold
    # turn (no live history for this conversation); once a conversation is
    # underway, always actually think with the context in hand.
    if not history:
        cached = load_learned_answer(root, prompt)
        if cached is not None:
            return {"answer": cached, "consulted": False, "from_memory": True, "contributors": []}

    # Short-term conversation history goes FIRST in the context so the
    # persona reads it as the thread it's continuing. Then the durable
    # memory file and any away-mode context.
    context_note = "\n\n".join(
        part for part in (history, _load_memory_notes(root), _recent_away_context(root)) if part
    ) or None

    # Notice and save a durable fact from this message on its own (not
    # just when told "remember ..."). Best-effort and gated by a cheap
    # pre-filter, so it costs nothing on the overwhelming majority of
    # turns and never affects the reply.
    autosaved_note = await maybe_autosave_note(router, persona_name, prompt, root)

    primary_result = await router.route(persona_name, prompt, system=context_note)
    if not primary_result.ok:
        return {
            "answer": f"[error: {primary_result.error}]",
            "consulted": False,
            "from_memory": False,
            "contributors": [],
        }

    # Consult either because the primary looked uncertain, or -- since an
    # abliterated primary rarely hedges in words even when it's wrong --
    # because this message landed in the random sample kept for passive
    # learning-log data collection (persona.consult_sample_rate, default
    # off). Sampled consults still only log if a consult model actually
    # came back confident; see the `confident` check below.
    sampled = consult_sample_rate > 0 and random.random() < consult_sample_rate
    if not seems_uncertain(primary_result.text) and not sampled:
        return {
            "answer": primary_result.text,
            "consulted": False,
            "from_memory": False,
            "contributors": [],
            "autosaved_note": autosaved_note,
        }

    # Uncertain (or sampled) -- first pass: ONE model, picked by topic, not
    # a broadcast to the whole consult roster. `consult_models` used to be
    # queried all at once here; on an 8GB card that meant up to 20+ local
    # models loading one at a time (broadcast() already serializes local
    # GGUF calls to avoid a VRAM OOM) for a single question -- correct, but
    # so slow it made a real consult round take hours. Classifying the
    # question's topic and routing to just the best-fit specialist for
    # that topic (see gremlin_core/specialists.py's `specialists:` config
    # block) gets the same "many models, each good at something" roster
    # without the fan-out cost: one model call instead of twenty.
    specialist_registry = specialists_mod.SpecialistRegistry.from_config(router.registry.raw_config)
    task_type = specialists_mod.classify_task_type(prompt)
    candidates = specialist_registry.for_task(task_type)

    # Ask gremlin itself (still resident -- see _deliberate_candidate's
    # docstring) which of this group's own models best fits THIS prompt,
    # before freeing any VRAM for it. Bumps that pick to the front by
    # priority so specialists.route tries it first; the rest of the
    # group -- including the big lead -- stays as the normal
    # error/empty-response fallback chain, just re-anchored around it.
    if candidates:
        chosen_name = await _deliberate_candidate(router, persona_name, prompt, candidates)
        if chosen_name:
            candidates = [
                dataclasses.replace(c, priority=-1) if c.name == chosen_name else c
                for c in candidates
            ]
            specialist_registry = specialists_mod.SpecialistRegistry(candidates)

    # Free the primary's VRAM first if the picked topic's candidates are
    # local GGUF models -- on a card where primary + even one local model
    # wouldn't both fit resident at once, this is what actually lets the
    # call run at all, not just what keeps VRAM from accumulating over
    # time (eviction.py's job). The primary reloads on its own via the
    # normal warmup() path the next time it's used.
    if candidates and any(router.registry.get(c.name).info.kind == "local_gguf" for c in candidates):
        primary_name = router.registry.primary_model_name()
        if primary_name:
            await router.registry.get(primary_name).unload()

    confident: dict = {}
    escalated = False
    if candidates:
        routing = await specialists_mod.route(
            router, router.registry, specialist_registry, task_type, prompt,
        )
        if routing.routed and routing.findings and not seems_uncertain(routing.findings):
            confident = {
                routing.specialist_used: GenerationResult(model=routing.specialist_used, text=routing.findings),
            }
        # The specialist's text is already captured above -- its weights
        # don't need to stay resident. Without this, nothing ever frees
        # them: eviction.py's idle sweep only runs under `gremlin serve`,
        # not one-shot CLI commands like `gremlin distill`, so a
        # long-running batch accumulated a DIFFERENT specialist's VRAM on
        # every consult with nothing giving it back, until even the
        # primary's own reload for the synthesis call below (or the next
        # prompt's first call) failed outright -- confirmed by testing to
        # be the real cause of "Failed to load model from file" errors
        # that looked like vague hardware degradation but were actually
        # just an accumulating VRAM leak.
        if routing.specialist_used:
            try:
                await router.registry.get(routing.specialist_used).unload()
            except Exception:
                pass

    # Nobody in the first pass actually knew -- try the dedicated last resort
    if not confident and last_resort_model:
        last_resort_result = await router.route(last_resort_model, prompt)
        last_resort_confident = _confident_results({last_resort_model: last_resort_result})
        if last_resort_confident:
            confident = last_resort_confident
            escalated = True

    if not confident:
        # Nobody could help, anywhere -- return the original uncertain
        # answer honestly rather than pretending consultation fixed anything.
        return {
            "answer": primary_result.text,
            "consulted": True,
            "from_memory": False,
            "contributors": [],
            "note": "consulted but nobody -- including the last-resort check -- had a confident answer",
        }

    # Hand the gathered material to Gremlin itself for the final answer,
    # so the voice is always its own, never a raw forward of another model.
    research_text = "\n\n".join(f"=== source ===\n{r.text}" for r in confident.values())
    synth_prompt = f"Original question: {prompt}\n\nGathered research:\n{research_text}"
    synth_system = f"{context_note}\n\n{CONSULT_SYNTHESIS_PROMPT}" if context_note else CONSULT_SYNTHESIS_PROMPT
    synthesis = await router.route(persona_name, synth_prompt, system=synth_system)
    final_answer = synthesis.text if synthesis.ok else next(iter(confident.values())).text

    append_learning_log(root, {
        "prompt": prompt,
        "primary_uncertain_answer": primary_result.text,
        "consulted_models": list(confident.keys()),
        # Raw per-model text, not just names -- the actual distillation
        # material for fine-tuning Gremlin's own primary model on what
        # the consult group contributed. final_answer (below) stays the
        # training target, since that's already in Gremlin's own voice;
        # this is kept alongside it for inspection/debugging, not as
        # something a dataset builder should train on directly.
        "consulted_texts": {name: r.text for name, r in confident.items()},
        "escalated_to_last_resort": escalated,
        "final_answer": final_answer,
    })

    return {
        "answer": final_answer,
        "consulted": True,
        "from_memory": False,
        "contributors": list(confident.keys()),
        "escalated": escalated,
        "autosaved_note": autosaved_note,
    }
